# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # No tests yet
      #- name: Unit tests
      #  run: npm run test

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"

      - name: Git tag
        run: |
          export UIKIT_VERSION=$(cat ./package.json | jq '.version' | sed -e 's/"//' -e 's/"//')
          git tag ${UIKIT_VERSION}
          git push https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/icgc-argo/uikit --tags
